#!/bin/sh
cd /home/pi/Projects/flowercare

exec &> capture.txt
tail -f capture.txt >/dev/tty7 &
node flowerServer.js &
sleep 5 & 
pagekite.py 8000 dabi.pagekite.me &
wait
echo all processes closed



