#!/bin/sh
#/etc/init.d/myService
export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

case "$1" in
start)
exec sudo -u pi screen -d -m /home/pi/Projects/flowercare/startupScript
;;
stop)
	SESSIONPID=$(exec sudo -u pi screen -list | grep Detached | awk -F "." '{print $1}')
	exec sudo -u pi echo $SESSIONPID&
	exec sudo -u pi echo "li morti de mammeta"&
	exec sudo -u pi screen -S $SESSIONPID -X quit
;;
*)
echo "Usage: /etc/init.d/flowercara {start|stop}"
exit 1
;;
esac
exit 0
